title: Diana Koulakhmetova # your name (or website title) her
logo: "/images/81f7e4c5-d5ce-46b4-b5c3-a6da2b413de1.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  * Data Scientist with 4 years of experience in the financial sphere and governmental projects.
  * Strong proficiency in Python, SQL, Hadoop, and Power BI.
  * Proven track record of developing prediction models, including phishing prevention, fraud prevention, scoring models, and clients' segmentation algorithms.
  * Skilled in data preparation using Oracle PL/SQL and data visualization using Power BI for extracting valuable business insights.
  * Experienced in data governance, maintenance, and audit of data sources.
  * Excellent communication, writing skills, and ability to quickly perceive and process information.
  * Team player with Agile team experience.
  <br><br>
  * Master of Science degree in Data Science and Financial Technology from the University of London, Goldsmiths.
  * Double Bachelor's degrees in Economics and Mathematics from the University of London, and Mathematics and Computer Modeling from Kazakh-British Technical University.
  * Researcher at The National Academy of Sciences of Kazakhstan, Institute of Theoretical and Applied Mathematics, with participation in governmental projects and statistical analysis of financing and implementation of scientific projects.
  * IELTS certification of C1 level with 7.5 points.
  <br><br>
  <a href="https://www.linkedin.com/in/diana-koulakhmetova/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: 5028009036 # your Google Analytics tracking ID here
